### ISSUE TITLE
可以在py3.6上编译吗

### ISSUE THREAD

**Issue by livecle** [wqh17101/zbar_lite#2]
你好，感谢你的工作和分享，
（1）我尝试了在python3.6环境下进行编译，但是编译出的whl文件，安装后，import 的zbar文件里面是空的，请问这是什么原因呢？
（2）可以提供下python3.6的whl文件吗

**Comment by wqh17101** [comment]
@livecle 我理解应该没啥问题，可以编译的。
什么叫zbar文件是空的,

**Comment by livecle** [comment]
谢谢作者，我刚刚又按照文档说明重新编译了一次，这次成功了。
